name: Simple Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Kód letöltése
        uses: actions/checkout@v2

      - name: Fájl ellenőrzés
        run: ls -la

      - name: Build step
        run: |
          mkdir build
          cp index.html build/
          cp style.css build/